config/routes.rb
Rails.application.routes.draw do
   

   root "pages#index"
   devise_for :users, skip: [:sessions]
   as :user do
      get 'login', to: 'pages#login', as: :new_user_session
      get 'logout', to: 'devise/sessions#destroy', as: :destroy_user_session
   end

   post "/user_login", to: "login#user_login"

   
   namespace :admin do
      resources :areas
      resources :clusters
      resources :branches
      resources :employees
      resources :job_levels
      post "/create_area", to: "areas#create"
      post "/create_cluster",to: "clusters#create"
      post "/create_branch", to: "branches#create"
      post "/create_job_levels", to: "job_levels#create"
   end
 


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/area.rb
class Area < ApplicationRecord

	has_many :clusters , dependent: :delete_all
end

app/models/branch.rb
class Branch < ApplicationRecord
	belongs_to :cluster
	has_many :employees
end

app/models/cluster.rb
class Cluster < ApplicationRecord
	belongs_to :area
	has_many :branches, dependent: :delete_all


end

app/models/employee.rb
class Employee < ApplicationRecord


	def full_name
		"#{first_name.upcase} #{last_name.upcase}"
	end

	def age 
    if self.birthday.nil?
      "Please set date of birth"
    else
      begin
        now = Time.now.utc.to_date
        now.year - self.birthday.year - ((now.month > self.birthday.month || (now.month == self.birthday.month && now.day >= self.birthday.day)) ? 0 : 1)
        #now.year - self.date_of_birth.year - (self.date_of_birth.to_date.change(:year => now.year) > now ? 1 : 0)
      rescue Exception
        "Invalid date of birth: #{self.birthday}"
      end 
    end 
  end
end

app/models/job_level.rb
class JobLevel < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,:recoverable, 
  :rememberable, :validatable, :trackable , :timeoutable

  belongs_to :employee

  def user_object
    {
      email: email
    }
  end
end

app/controllers/admin/areas_controller.rb
module Admin
	class AreasController < ApplicationController
		before_action :authenticate_user!
		def index
			@areas = Area.select("*")

			@subheader_side_actions = [
	        {
	          id: "btn-new",
	          link: "#",
	          class: "fa fa-plus",
	          text: "New Area"
	        }
	      ]
		end


		def create
			@area_name = params[:area_name]
			@area_shortname = params[:area_shortname]
			config = {
			area_name: @area_name,
			area_shortname: @area_shortname
			}
			errors = ::Admin::ValidateCreateArea.new(config: config).execute!

			if errors[:full_messages].any?
				  render json: errors, status: 400
			else
				area = ::Admin::CreateArea.new(config: config).execute!
				render json: {message: "success"}
			end


		end
	end
end

app/controllers/admin/branches_controller.rb
module Admin
	class BranchesController < ApplicationController
		before_action :authenticate_user!
		
		def index
			@branch = Branch.select("*")
			@clusters = Cluster.select("*")

			@subheader_side_actions = [
	        {
	          id: "btn-new",
	          link: "#",
	          class: "fa fa-plus",
	          text: "New Branch"
	        }
	      ]
		end

		def create
			branch_name = params[:branch_name]
			branch_shortname = params[:branch_shortname]
			cluster_id = params[:selected_cluster]

			config = {
				branch_name: branch_name,
				branch_shortname: branch_shortname,
				cluster_id: cluster_id
			}

			errors = ::Admin::ValidateCreateBranch.new(config: config).execute!

			if errors[:full_messages].any?
				render json: errors, status: 400
			else
				branch = ::Admin::CreateBranch.new(config: config).execute!
				render json: {message: "success"}
			end


		end
	
	end
end

app/controllers/admin/clusters_controller.rb
module Admin
	class ClustersController < ApplicationController
			before_action :authenticate_user!
		def index
			@clusters = Cluster.select("*")
			@area = Area.select("*")

			@subheader_side_actions = [
	        {
	          id: "btn-new",
	          link: "#",
	          class: "fa fa-plus",
	          text: "New Cluster"
	        }
	      ]
		end

		def show
			
		end
		def create
			cluster_name = params[:cluster_name]
			cluster_shortname = params[:cluster_shortname]
			area_id = params[:selected_area]

			config = {
				cluster_name: cluster_name,
				cluster_shortname: cluster_shortname,
				selected_area: area_id
			}

			errors = ::Admin::ValidateCreateCluster.new(config: config).execute!
			if errors[:full_messages].any?
				render json: errors, status: 400
			else
				cluster = ::Admin::CreateCluster.new(config: config).execute!
				render json: {message: "success"}
			end


		end
	end
end

app/controllers/admin/employees_controller.rb
module Admin
	class EmployeesController < ApplicationController
		def index
			@employees = Employee.select("*")
		end
	end
end

app/controllers/admin/job_levels_controller.rb
module Admin
	class JobLevelsController < ApplicationController
		before_action :authenticate_user!
	
	def index
		@job_levels = JobLevel.select("*")
		@kso_settings = Settings[:kso_org]
		@subheader_side_actions = [
	        {
	          id: "btn-new",
	          link: "#",
	          class: "fa fa-plus",
	          text: "Create Job Level"
	        }
	      ]
	end

	def create
		job_level_name = params[:job_level_name]
		select_kso = params[:select_kso]

		config = {
			job_level_name: job_level_name,
			select_kso: select_kso
		}

		errors = ::Admin::ValidateCreateJobLevel.new(config: config).execute!

		if errors[:full_messages].any?
			render json: errors, status: 400
		else
			job_level = ::Admin::CreateJobLevel.new(config: config).execute!
			render json: {message: "Success"}
		end

	end


	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
	before_action :authenticate_user!
	def index

	end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
	def user_login
		username = params[:username]
		password = params[:password]
		
		config = {
			username: username,
			password: password
		}
		
		errors = ::Users::ValidateLogin.new(config: config)
		errors.execute!

		if errors.errors.any?
		 render json: errors,status: 400
		else
			sign_in(:user, errors.user)
			
		 render json: {user: errors.user.user_object}
		end

	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	before_action :authenticate_user!, except: [:login, :forgot_password, :ping]
	def index
		
	end
	def login
		 render 'pages/login', layout: 'landing'
	end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/admin/areas/_index_list.html.haml
%table#data-table.display.table.table-bordered.table-hover.table-sm
  %thead
    %tr
      %th
        Name
      %th
        Short Name
      %th
        Actions
  %tbody
    - @areas.each do |area|
      %tr
        %td
          #{area.name.upcase}
        %td
          #{area.short_name.upcase}

        %td{style: "width: 150px"}
          .btn-group-vertical{style: "width: 150px"}
            = link_to admin_area_path(area), class: 'btn btn-sm btn-primary btn-block' do
              .bi.bi-search
              Show
            = link_to edit_admin_area_path(area), class: 'btn btn-sm btn-info btn-block' do
              .bi.bi-pencil-fill
              Edit
        

app/views/admin/areas/edit.html.haml
%h4
	EDIT

app/views/admin/areas/index.html.haml
%main.c-main
  .container-fluid
    .row
      .col
        .card
          .card-body
            - if @areas.any?
              = render partial: "index_list"
            - else
              %p
                No areas found
=render partial: "admin/areas/modals/new"

app/views/admin/areas/modals/_new.html.haml
#modal-new.modal.fade
  .modal-dialog.modal-lg
    .modal-content
      .modal-header
        %h3.modal-title
          Create Area
      .modal-body
        .modal-body-content
          .row
            .col
              .form-group
                %label
                  Area Name
                %input#area-name.form-control
          .row
            .col
              .form-group
                %label
                  Area Shortname
                %input#area-shortname.form-control
      .modal-footer
        .controls
          %button#btn-save.btn.btn-primary
            .fa.fa-check
            Save
          %button.btn{"data-bs-dismiss" => "modal", :type => "button"}
            .fa.fa-times
            Cancel

app/views/admin/areas/show.html.haml
%main.c-main
  .container-fluid
    .row
      .col
        .card
          .card-body
          

app/views/admin/branches/_index_list.html.haml
%table#data-table.display.table.table-bordered.table-hover.table-sm
  %thead
    %tr
      %th
        Name
      %th
        Short Name
      %th
        Cluster
      %th
        Area
      %th
        Actions
  %tbody
    - @branch.each do |branch|
      %tr
        %td
          #{branch.name.upcase}
        %td
          #{branch.short_name.upcase}
        %td
          #{branch.cluster.name.upcase}
        %td
          #{Cluster.find(branch.cluster_id).area.name.upcase}
        %td{style: "width: 150px"}
          .btn-group-vertical{style: "width: 150px"}
            = link_to admin_branch_path(branch), class: 'btn btn-sm btn-primary btn-block' do
              .bi.bi-search
              Show
            = link_to edit_admin_branch_path(branch), class: 'btn btn-sm btn-info btn-block' do
              .bi.bi-pencil-fill
              Edit
        

app/views/admin/branches/index.html.haml
%main.c-main
  .container-fluid
    .row
      .col
        .card
          .card-body
            - if @branch.any?
              = render partial: "index_list"
            - else
              %p
                No areas found

=render partial: "admin/branches/modals/new"

app/views/admin/branches/modals/_new.html.haml
#modal-new.modal.fade
  .modal-dialog.modal-lg
    .modal-content
      .modal-header
        %h3.modal-title
          Create Branch
      .modal-body
        .modal-body-content
          .row
            .col
              .form-group
                %label
                  Branch Name
                %input#branch-name.form-control
          .row
            .col
              .form-group
                %label
                  Branch Shortname
                %input#branch-shortname.form-control
          .row
            .col
              .form-group
                %label
                  Select Cluster:
                = select_tag :clusters, options_for_select(@clusters.collect{ |u| [u[:name].upcase,u[:id]] }), id: "select-cluster", class: "form-control" , prompt: "-- SELECT --"
      .modal-footer
        .controls
          %button#btn-save.btn.btn-primary
            .fa.fa-check
            Save
          %button.btn{"data-bs-dismiss" => "modal", :type => "button"}
            .fa.fa-times
            Cancel

app/views/admin/clusters/_index_list.html.haml
%table#data-table.display.table.table-bordered.table-hover.table-sm
  %thead
    %tr
      %th
        Name
      %th
        Short Name
      %th
        Area
      %th
        Actions
  %tbody
    %tbody
    - @clusters.each do |cluster|
      %tr
        %td
          #{cluster.name.upcase}
        %td
          #{cluster.short_name.upcase}
        %td
          #{Cluster.find(cluster.id).area.name}

        %td{style: "width: 150px"}
          .btn-group-vertical{style: "width: 150px"}
            = link_to admin_cluster_path(cluster), class: 'btn btn-sm btn-primary btn-block' do
              .bi.bi-search
              Show
            = link_to edit_admin_cluster_path(cluster), class: 'btn btn-sm btn-info btn-block' do
              .bi.bi-pencil-fill
              Edit

        

app/views/admin/clusters/index.html.haml
%main.c-main
  .container-fluid
    .row
      .col
        .card
          .card-body
            - if @clusters.any?
              = render partial: "index_list"
            - else
              %p
                No areas found
=render partial: "admin/clusters/modals/new"

app/views/admin/clusters/modals/_new.html.haml
#modal-new.modal.fade
  .modal-dialog.modal-lg
    .modal-content
      .modal-header
        %h3.modal-title
          Create Cluster
      .modal-body
        .modal-body-content
          .row
            .col
              .form-group
                %label
                  Cluster Name
                %input#cluster-name.form-control
          .row
            .col
              .form-group
                %label
                  Cluster Shortname
                %input#cluster-shortname.form-control
          .row
            .col
              .form-group
                %label
                  Select Area:
                = select_tag :area, options_for_select(@area.collect{ |u| [u[:name].upcase,u[:id]] }), id: "select-area", class: "form-control" , prompt: "-- SELECT --"
      .modal-footer
        .controls
          %button#btn-save.btn.btn-primary
            .fa.fa-check
            Save
          %button.btn{"data-bs-dismiss" => "modal", :type => "button"}
            .fa.fa-times
            Cancel

app/views/admin/employees/_index_list.html.haml
%table#data-table.display.table.table-bordered.table-hover.table-sm
  %thead
    %tr
      %th
      %th.text-center
        Employee ID
      %th.text-center
        Employee Name
      %th.text-center
        Email Address
      %th.text-center
        Actions
  %tbody
    -@employees.each_with_index do |emp,index|
      %tr
        %td
          #{index + 1}
        %td.text-center
          #{emp[:employee_number]}
        %td.text-center
          #{Employee.find(emp[:id]).full_name}
        %td.text-center
          #{emp[:email_address]}
        %td.text-center{style: "width: 150px"}
          .btn-group-vertical{style: "width: 150px"}
            = link_to admin_employee_path(emp), class: 'btn btn-sm btn-primary btn-block' do
              .bi.bi-search
              Details

app/views/admin/employees/index.html.haml
%main.c-main
  .container-fluid
    .row
      .col
        .card
          .card-body
            - if @employees.any?
              = render partial: "index_list"
            - else
              %p
                No Employee's Found

app/views/admin/job_levels/_index_list.html.haml
%table#data-table.display.table.table-bordered.table-hover.table-sm
  %thead
    %tr
      %th
        Name
      %th
        KSO
      %th
        Actions
  %tbody
    - @job_levels.each do |job_levels|
      %tr
        %td
          #{job_levels.name.upcase}
        %td
          - Settings[:kso_org].each do |kso|
            -if kso[:id] == job_levels.kso_id
              #{kso[:name]}
        %td{style: "width: 150px"}
          .btn-group-vertical{style: "width: 150px"}
            = link_to admin_job_level_path(job_levels), class: 'btn btn-sm btn-primary btn-block' do
              .bi.bi-search
              Show
            = link_to edit_admin_job_level_path(job_levels), class: 'btn btn-sm btn-info btn-block' do
              .bi.bi-pencil-fill
              Edit
        

app/views/admin/job_levels/index.html.haml
%main.c-main
  .container-fluid
    .row
      .col
        .card
          .card-body
            - if @job_levels.any?
              = render partial: "index_list"
            - else
              %p
                No Job Levels Found
=render partial: "admin/job_levels/modals/new"

app/views/dashboard/index.html.haml
%h3
	WELCOME

app/views/shared/_sidebar.html.haml
.sidebar
	= link_to root_path do
		.logo-details
			%i.bi.bi-house-door
			%span.logo-name
				MMD SYSTEM
	%ul.nav-links
		%li{ class: "#{params[:controller] == 'pages' and params[:action] == 'index' ? 'active' : ''}" }
			= link_to root_path, class: "" do
				%i.bi.bi-speedometer
				%span.link-name
					Dashboard
		%li
			= link_to root_path, class: "" do
				%i.bi.bi-person-fill-add
				%span.link-name
					Sales Invoices Registry
		%li
			= link_to root_path, class: "" do
				%i.bi.bi-person-fill-add
				%span.link-name
					Collection

		%li{ class: "#{params[:controller] == '' ? 'active' : ''}" }
			.icon-link
				= link_to "#", class: "" do
					%i.bi.bi-gear
					%span.link-name
						Admin
				%i.bi.bi-caret-down.arrow
			%ul.sub-menu
				%li
					= link_to admin_employees_path, class: "" do
						%i.bi.bi-people-fill
							Employee
				%li
					= link_to admin_job_levels_path, class: "" do
						%i.bi.bi-person-workspace
							Job Level	
				%li
					= link_to "#", class: "", data: { "bs-toggle": "modal", "bs-target": "#modal-nav-admin" } do
						%i.bi.bi-diagram-2-fill
							Department
				%li
					= link_to "#", class: "", data: { "bs-toggle": "modal", "bs-target": "#modal-nav-admin" } do
						%i.bi.bi-table
							Salary Table
				%li
					= link_to admin_areas_path, class: "" do
						%i.bi.bi-globe2
							Area
				%li
					= link_to admin_clusters_path, class: "" do
						%i.bi.bi-map-fill
							Cluster
				%li
					= link_to admin_branches_path, class: "" do
						%i.bi.bi-pin-map-fill
							Branches
				%li
					= link_to "#", class: "", data: { "bs-toggle": "modal", "bs-target": "#modal-nav-admin" } do
						%i.bi.bi-person-lock
							Users
				%li
					= link_to "#", class: "", data: { "bs-toggle": "modal", "bs-target": "#modal-nav-admin" } do
						%i.bi.bi-journal-check
							Exams
		%li
			.profile-details
				= link_to "#" do
					.profile-content
						= image_tag "image.jpg"
					.name-job
						.profile-name
							#{current_user.email}
						.job
							#{current_user.employee.full_name}
				= link_to destroy_user_session_path do
					%i.bi.bi-box-arrow-left
							

app/views/shared/_subheader.html.haml
- if side_actions.any?
  %ul.navbar-nav.me-auto.mb-2.mb-lg-0
    - side_actions.each do |a|
      %li.nav-item
        = link_to a[:link], class: "nav-link", id: "#{a[:id]}", data: a[:data] do
          %div{ class: "c-icon #{a[:class]}" }
          #{a[:text]}

app/views/shared/_top_navigation.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.sticky-top{ style: "background-color: #13415F" }
  .container-fluid
    = link_to "#", class: "navbar-brand" do
      %i.bi.bi-menu.bi-list
    = render partial: "shared/subheader", locals: { side_actions: @subheader_side_actions  || [] }